# Generated by Django 4.2.2 on 2024-02-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('place', models.CharField(max_length=100)),
                ('gen', models.CharField(max_length=50)),
                ('status', models.TextField()),
            ],
        ),
    ]
