# Generated by Django 4.2.2 on 2024-02-11 12:29

from django.db import migrations, models
import jonjo.models


class Migration(migrations.Migration):

    dependencies = [
        ('jonjo', '0002_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=jonjo.models.save_landing_image, verbose_name='Category image')),
            ],
        ),
    ]
