# Generated by Django 4.2.2 on 2024-02-14 10:52

from django.db import migrations, models
import jonjo.models


class Migration(migrations.Migration):

    dependencies = [
        ('jonjo', '0003_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=jonjo.models.save_logo_image, verbose_name='Category image')),
            ],
        ),
        migrations.CreateModel(
            name='VideoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=jonjo.models.save_videobanner, verbose_name='Video')),
            ],
        ),
    ]
