# Generated by Django 4.0.1 on 2024-11-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jonjo', '0004_logo_videobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
